export const scoring = {
  q1: {
    gift_special: {
      round_bouquet: 3,
      clutch_bouquet: 4,
      seasonal_bouquet: 2,
      seasonal_event_bouquet: 2,
      pot_arrangement: 3,
      seasonal_arrangement: 2,
      mall_cake: 3,
      full_order: 5,
    },
    gift_friend: {
      round_bouquet: 4,
      clutch_bouquet: 3,
      casual_clutch: 3,
      seasonal_bouquet: 2,
      seasonal_event_bouquet: 2,
      pot_arrangement: 4,
      seasonal_arrangement: 2,
      single_flower: 3,
      mall_cake: 4,
      rabidoll: 3,
      order_rabidoll: 3,
      monthly_charm: 2,
      rose_charm: 3,
      alphabet_charm: 3,
      full_order: 1,
    },
    reward_myself: {
      round_bouquet: 1,
      clutch_bouquet: 1,
      casual_clutch: 1,
      seasonal_bouquet: 2,
      seasonal_event_bouquet: 2,
      pot_arrangement: 2,
      seasonal_arrangement: 2,
      single_flower: 1,
      mall_cake: 1,
      rabidoll: 3,
      order_rabidoll: 3,
      monthly_charm: 3,
      rose_charm: 3,
      alphabet_charm: 2,
      full_order: 1,
    },
    oshi: {
      casual_clutch: 2,
      pot_arrangement: 2,
      mall_cake: 1,
      rabidoll: 5,
      order_rabidoll: 5,
      rose_charm: 3,
      alphabet_charm: 5,
      full_order: 1,
    },
    special_event: {
      round_bouquet: 1,
      seasonal_bouquet: 1,
      seasonal_event_bouquet: 1,
      seasonal_arrangement: 1,
      celebration_flower: 5,
      mall_cake: 2,
      full_order: 5,
    },
  },

  q2: {
    cute: {
      round_bouquet: 3,
      clutch_bouquet: 1,
      casual_clutch: 1,
      seasonal_bouquet: 1,
      seasonal_event_bouquet: 1,
      pot_arrangement: 2,
      seasonal_arrangement: 1,
      single_flower: 2,
      celebration_flower: 2,
      mall_cake: 3,
      rabidoll: 3,
      order_rabidoll: 3,
      alphabet_charm: 2,
    },
    korean: {
      round_bouquet: 3,
      clutch_bouquet: 1,
      pot_arrangement: 2,
      single_flower: 1,
      celebration_flower: 1,
      mall_cake: 2,
      rabidoll: 3,
      order_rabidoll: 3,
      monthly_charm: 1,
      rose_charm: 1,
      alphabet_charm: 2,
    },
    stylish: {
      round_bouquet: 2,
      clutch_bouquet: 3,
      casual_clutch: 1,
      pot_arrangement: 2,
      single_flower: 1,
      celebration_flower: 2,
      mall_cake: 1,
      monthly_charm: 2,
      rose_charm: 1,
    },
    seasonal: {
      seasonal_bouquet: 3,
      seasonal_event_bouquet: 3,
      seasonal_arrangement: 3,
      single_flower: 1,
      monthly_charm: 3,
    },
  },

  q3: {
    portable: {
      single_flower: 2,
      rabidoll: 3,
      order_rabidoll: 3,
      monthly_charm: 3,
      rose_charm: 3,
      alphabet_charm: 3,
    },
    display: {
      round_bouquet: 2,
      clutch_bouquet: 2,
      casual_clutch: 2,
      seasonal_bouquet: 2,
      seasonal_event_bouquet: 2,
      pot_arrangement: 3,
      seasonal_arrangement: 3,
      mall_cake: 3,
    },
    bouquet: {
      round_bouquet: 3,
      clutch_bouquet: 3,
      casual_clutch: 3,
      seasonal_bouquet: 3,
      seasonal_event_bouquet: 3,
      pot_arrangement: 3,
      seasonal_arrangement: 3,
    },
    special_big: {
      seasonal_bouquet: 1,
      seasonal_event_bouquet: 1,
      seasonal_arrangement: 1,
      celebration_flower: 3,
      mall_cake: 2,
      full_order: 3,
    },
  },

  q4: {
    under1000: {
      round_bouquet: -3,
      clutch_bouquet: -3,
      casual_clutch: -2,
      seasonal_bouquet: -3,
      seasonal_event_bouquet: -3,
      pot_arrangement: -3,
      seasonal_arrangement: -3,
      single_flower: 3,
      celebration_flower: -2,
      mall_cake: -4,
      monthly_charm: 3,
      rose_charm: 3,
      alphabet_charm: 3,
      full_order: -5,
    },
    "1000_2000": {
      round_bouquet: -2,
      clutch_bouquet: -2,
      casual_clutch: -1,
      seasonal_bouquet: -2,
      seasonal_event_bouquet: -2,
      pot_arrangement: -2,
      seasonal_arrangement: -2,
      single_flower: -1,
      celebration_flower: -1,
      mall_cake: -3,
      rabidoll: 3,
      order_rabidoll: 3,
      full_order: -4,
    },
    "2000_3000": {
      round_bouquet: -1,
      clutch_bouquet: -1,
      casual_clutch: 3,
      seasonal_bouquet: -1,
      seasonal_event_bouquet: -1,
      pot_arrangement: -1,
      seasonal_arrangement: -1,
      single_flower: -2,
      celebration_flower: -2,
      mall_cake: -2,
      rabidoll: -1,
      order_rabidoll: -1,
      monthly_charm: -2,
      rose_charm: -2,
      alphabet_charm: -2,
      full_order: -3,
    },
    "3000_4500": {
      round_bouquet: 3,
      clutch_bouquet: 3,
      casual_clutch: -1,
      seasonal_bouquet: 3,
      pot_arrangement: 3,
      seasonal_arrangement: 3,
      single_flower: -3,
      celebration_flower: -3,
      mall_cake: -1,
      rabidoll: -2,
      order_rabidoll: -2,
      monthly_charm: -3,
      rose_charm: -3,
      alphabet_charm: -3,
      full_order: -2,
    },
    no_limit: {
      round_bouquet: -1,
      clutch_bouquet: -1,
      casual_clutch: -2,
      seasonal_bouquet: -1,
      seasonal_event_bouquet: 3,
      pot_arrangement: -1,
      seasonal_arrangement: -1,
      single_flower: -1,
      celebration_flower: 3,
      mall_cake: 3,
      rabidoll: -3,
      order_rabidoll: -3,
      monthly_charm: -3,
      rose_charm: -3,
      alphabet_charm: -3,
      full_order: 5,
    },
  },

  q5: {
    birthday: {
      round_bouquet: 5,
      clutch_bouquet: 3,
      casual_clutch: 2,
      seasonal_bouquet: 2,
      pot_arrangement: 2,
      seasonal_arrangement: 2,
      mall_cake: 5,
    },
    small_celebration: {
      round_bouquet: 3,
      clutch_bouquet: 3,
      casual_clutch: 5,
      seasonal_bouquet: 1,
      pot_arrangement: 2,
      seasonal_arrangement: 1,
      single_flower: 3,
      rabidoll: 3,
      order_rabidoll: 3,
      monthly_charm: 3,
      rose_charm: 3,
      alphabet_charm: 3,
    },





    season_event: {
      seasonal_bouquet: 5,
      seasonal_event_bouquet: 5,
      seasonal_arrangement: 5,
      monthly_charm: 5,
      alphabet_charm: 1,
    },
    wedding: {
      round_bouquet: 1,
      clutch_bouquet: 1,
      seasonal_bouquet: 1,
      seasonal_event_bouquet: 2,
      pot_arrangement: 2,
      seasonal_arrangement: 2,
      celebration_flower: 5,
      mall_cake: 3,
      full_order: 5,
    },
  },

  q6: {
    leave: {
      round_bouquet: 1,
      clutch_bouquet: 1,
      casual_clutch: 1,
      seasonal_bouquet: 3,
      seasonal_event_bouquet: 3,
      pot_arrangement: 1,
      seasonal_arrangement: 3,
      single_flower: 1,
      mall_cake: 1,
      rabidoll: 3,
      monthly_charm: 3,
      rose_charm: 1,
      alphabet_charm: 1,
    },
    semi_custom: {
      round_bouquet: 3,
      clutch_bouquet: 3,
      casual_clutch: 3,
      pot_arrangement: 3,
      mall_cake: 3,
      rose_charm: 1,
      alphabet_charm: 3,
    },
    full_custom: {
      celebration_flower: 5,
      mall_cake: 2,
      order_rabidoll: 5,
      alphabet_charm: 3,
      full_order: 5,
    },
  },
} as const;
